USE trubadur;

DELETE FROM rhythm_bar_occurrences     WHERE rhythm_bar_id > 0;
DELETE FROM rhythm_feature_occurrences WHERE rhythm_feature_id > 0;
DELETE FROM rhythm_features            WHERE id > 0;

/* INSERT IGNORE rhythm_bars */
INSERT  IGNORE INTO `rhythm_bars` VALUES (1,'[{\"type\": \"bar\"}]',0,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (2,'[{\"type\": \"n\", \"value\": 4}]',1,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (3,'[{\"type\": \"r\", \"value\": 4}]',1,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (4,'[{\"type\": \"n\", \"value\": 2}]',2,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (5,'[{\"dot\": true, \"type\": \"n\", \"value\": 2}]',3,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (6,'[{\"type\": \"r\", \"value\": 2}]',2,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (7,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',1,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (8,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"r\", \"value\": 8}]',1,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (9,'[{\"type\": \"r\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',1,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (10,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}]',2,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (11,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',2,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (12,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',4,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (13,'[{\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',1,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (14,'[{\"type\": \"r\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',1,0,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (15,'[{\"type\": \"n\", \"value\": 4}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 4}]',2,1,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (16,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',2,1,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (17,'[{\"type\": \"n\", \"value\": 2}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 4}]',3,2,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (18,'[{\"type\": \"n\", \"value\": 4}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 2}]',3,1,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (19,'[{\"dot\": true, \"type\": \"n\", \"value\": 4}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (20,'[{\"dot\": true, \"type\": \"r\", \"value\": 4}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (21,'[{\"dot\": true, \"type\": \"n\", \"value\": 4}, {\"type\": \"bar\"}, {\"dot\": true, \"tie\": true, \"type\": \"n\", \"value\": 4}]',3,1.5,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (22,'[{\"dot\": true, \"type\": \"n\", \"value\": 4}, {\"type\": \"bar\"}, {\"dot\": true, \"tie\": true, \"type\": \"n\", \"value\": 2}]',4.5,1.5,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (23,'[{\"dot\": true, \"type\": \"n\", \"value\": 2}, {\"type\": \"bar\"}, {\"dot\": true, \"tie\": true, \"type\": \"n\", \"value\": 4}]',4.5,3,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (24,'[{\"dot\": true, \"type\": \"r\", \"value\": 2}]',3,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (25,'[{\"dot\": true, \"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (26,'[{\"type\": \"n\", \"value\": 8}, {\"dot\": true, \"type\": \"n\", \"value\": 4}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (27,'[{\"dot\": true, \"type\": \"r\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (28,'[{\"type\": \"n\", \"value\": 8}, {\"dot\": true, \"type\": \"r\", \"value\": 4}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (29,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}]',3,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (30,'[{\"type\": \"n\", \"value\": 2}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',3,2,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (31,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 2}]',3,1,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (32,'[{\"dot\": true, \"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 4}]',3,2,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (33,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}]',3,1,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (34,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (35,'[{\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (36,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 4}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (37,'[{\"type\": \"r\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (38,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"r\", \"value\": 4}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (39,'[{\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',3,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (40,'[{\"dot\": true, \"type\": \"n\", \"value\": 2}, {\"type\": \"bar\"}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',4.5,3,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (41,'[{\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',3,1.5,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (42,'[{\"dot\": true, \"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}, {\"tie\": true, \"type\": \"n\", \"value\": 4}]',3,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (43,'[{\"dot\": true, \"type\": \"r\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}, {\"tie\": true, \"type\": \"n\", \"value\": 4}]',3,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (44,'[{\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',1,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (45,'[{\"type\": \"n\", \"value\": 4}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (46,'[{\"dot\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}]',1,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (47,'[{\"dot\": true, \"type\": \"r\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}]',1,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (48,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',1,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (49,'[{\"type\": \"n\", \"value\": 4}, {\"dot\": true, \"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (50,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (51,'[{\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (52,'[{\"type\": \"n\", \"value\": 4}, {\"tie\": true, \"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (53,'[{\"dot\": true, \"type\": \"r\", \"value\": 4}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',2,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (54,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',3,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (55,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',2,1,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (56,'[{\"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 8}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (57,'[{\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 4}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (58,'[{\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (59,'[{\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (60,'[{\"type\": \"n\", \"value\": 8}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 8}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (61,'[{\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}, {\"tie\": true, \"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',3,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (62,'[{\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"r\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (63,'[{\"dot\": true, \"type\": \"n\", \"value\": 4}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}]',3,1.5,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (64,'[{\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 8}]',1.5,NULL,NULL);
INSERT  IGNORE INTO `rhythm_bars` VALUES (65,'[{\"type\": \"n\", \"value\": 4}, {\"type\": \"n\", \"value\": 8}, {\"type\": \"bar\"}, {\"tie\": true, \"type\": \"n\", \"value\": 8}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}, {\"type\": \"n\", \"value\": 16}]',3,1.5,NULL);

/* INSERT IGNORE bar_infos */
INSERT  IGNORE INTO `bar_infos` VALUES (1,'{\"base_note\": 4, \"num_beats\": 4}',11,0.6);
INSERT  IGNORE INTO `bar_infos` VALUES (2,'{\"base_note\": 4, \"num_beats\": 3}',11,0.6);
INSERT  IGNORE INTO `bar_infos` VALUES (3,'{\"base_note\": 8, \"num_beats\": 6}',11,0.6);
INSERT  IGNORE INTO `bar_infos` VALUES (4,'{\"base_note\": 4, \"num_beats\": 5, \"subdivisions\": [{\"d\": 4, \"n\": 3}, {\"d\": 4, \"n\": 2}]}',11,0.2);
INSERT  IGNORE INTO `bar_infos` VALUES (5,'{\"base_note\": 4, \"num_beats\": 5, \"subdivisions\": [{\"d\": 4, \"n\": 2}, {\"d\": 4, \"n\": 3}]}',11,0.2);

/*  INSERT rhythm_features */
INSERT INTO `rhythm_features` VALUES (1,'Level 11 (4/4) (3/4)',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (2,'Level 12 (4/4)',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (3,'Level 13 (4/4)(3/4)(mešano)',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (4,'Level 14 pavze (4/4)',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (5,'Level 1 crossbars',NULL,NULL,1);
INSERT INTO `rhythm_features` VALUES (6,'Level 11 crossbars (4/4) (3/4)',NULL,NULL,1);
INSERT INTO `rhythm_features` VALUES (9,'Level 11 (6/8)',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (10,'Level 11 crossbars (6/8)',NULL,NULL,1);
INSERT INTO `rhythm_features` VALUES (11,'Level 12 crossbars (4/4)',NULL,NULL,1);
INSERT INTO `rhythm_features` VALUES (12,'Level 12 (6/8)',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (13,'Level 12 crossbar (6/8)',NULL,NULL,1);
INSERT INTO `rhythm_features` VALUES (14,'Level 12 (5/4)',0,0,0);
INSERT INTO `rhythm_features` VALUES (15,'Level 13 crossbar (4/4)(3/4)(mešano)',NULL,NULL,1);
INSERT INTO `rhythm_features` VALUES (16,'Level 13 (6/8)',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (17,'Level 13 (6/8) crossbar',NULL,NULL,1);
INSERT INTO `rhythm_features` VALUES (18,'bar',NULL,NULL,1);
INSERT INTO `rhythm_features` VALUES (21,'F1',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (22,'F2',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (23,'F3',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (24,'F4N',1,NULL,0);
INSERT INTO `rhythm_features` VALUES (25,'F4R',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (26,'F1 8',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (27,'F2 8',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (28,'F3 8',NULL,NULL,0);
INSERT INTO `rhythm_features` VALUES (29,'F4N 8',1,NULL,0);
INSERT INTO `rhythm_features` VALUES (30,'F4R 8',NULL,NULL,0);

/*  INSERT rhythm_feature_occurrences */
INSERT INTO `rhythm_feature_occurrences` VALUES (11,18,1,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (11,18,2,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (11,18,3,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (11,21,1,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (11,21,2,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (11,26,3,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (12,18,1,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (12,18,2,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (12,18,3,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (12,22,1,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (12,22,2,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (12,27,3,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (13,18,1,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (13,18,2,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (13,18,3,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (13,23,1,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (13,23,2,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (13,27,3,0.6);
INSERT INTO `rhythm_feature_occurrences` VALUES (13,28,3,0.4);
INSERT INTO `rhythm_feature_occurrences` VALUES (14,18,1,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (14,18,2,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (14,18,3,1);
INSERT INTO `rhythm_feature_occurrences` VALUES (14,24,1,0.4);
INSERT INTO `rhythm_feature_occurrences` VALUES (14,24,2,0.4);
INSERT INTO `rhythm_feature_occurrences` VALUES (14,25,1,0.6);
INSERT INTO `rhythm_feature_occurrences` VALUES (14,25,2,0.6);
INSERT INTO `rhythm_feature_occurrences` VALUES (14,29,3,0.3);
INSERT INTO `rhythm_feature_occurrences` VALUES (14,30,3,0.7);

/*  INSERT rhythm_bar_occurrences */
INSERT INTO `rhythm_bar_occurrences` VALUES (2,21,0.8);
INSERT INTO `rhythm_bar_occurrences` VALUES (2,22,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (2,23,0.2);
INSERT INTO `rhythm_bar_occurrences` VALUES (2,25,0.4);
INSERT INTO `rhythm_bar_occurrences` VALUES (3,21,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (3,22,0.1);
INSERT INTO `rhythm_bar_occurrences` VALUES (3,23,0.1);
INSERT INTO `rhythm_bar_occurrences` VALUES (3,24,0.6);
INSERT INTO `rhythm_bar_occurrences` VALUES (4,21,0.4);
INSERT INTO `rhythm_bar_occurrences` VALUES (4,22,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (4,23,0.05);
INSERT INTO `rhythm_bar_occurrences` VALUES (5,21,0.6);
INSERT INTO `rhythm_bar_occurrences` VALUES (5,22,0.2);
INSERT INTO `rhythm_bar_occurrences` VALUES (5,26,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (5,27,0.2);
INSERT INTO `rhythm_bar_occurrences` VALUES (6,21,0.1);
INSERT INTO `rhythm_bar_occurrences` VALUES (6,22,0.05);
INSERT INTO `rhythm_bar_occurrences` VALUES (6,23,0.05);
INSERT INTO `rhythm_bar_occurrences` VALUES (6,24,0.1);
INSERT INTO `rhythm_bar_occurrences` VALUES (7,22,0.6);
INSERT INTO `rhythm_bar_occurrences` VALUES (7,23,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (7,25,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (8,22,0.15);
INSERT INTO `rhythm_bar_occurrences` VALUES (8,23,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (8,24,0.2);
INSERT INTO `rhythm_bar_occurrences` VALUES (9,22,0.15);
INSERT INTO `rhythm_bar_occurrences` VALUES (9,23,0.2);
INSERT INTO `rhythm_bar_occurrences` VALUES (9,24,0.2);
INSERT INTO `rhythm_bar_occurrences` VALUES (10,23,0.14);
INSERT INTO `rhythm_bar_occurrences` VALUES (11,22,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (13,23,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (14,25,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (19,26,0.6);
INSERT INTO `rhythm_bar_occurrences` VALUES (19,27,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (19,30,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (20,26,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (20,27,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (20,29,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (24,22,0.1);
INSERT INTO `rhythm_bar_occurrences` VALUES (24,26,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (24,27,0.25);
INSERT INTO `rhythm_bar_occurrences` VALUES (24,29,0.2);
INSERT INTO `rhythm_bar_occurrences` VALUES (25,23,0.4);
INSERT INTO `rhythm_bar_occurrences` VALUES (26,23,0.4);
INSERT INTO `rhythm_bar_occurrences` VALUES (27,23,0.25);
INSERT INTO `rhythm_bar_occurrences` VALUES (34,27,0.4);
INSERT INTO `rhythm_bar_occurrences` VALUES (35,27,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (35,30,0.4);
INSERT INTO `rhythm_bar_occurrences` VALUES (36,27,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (37,27,0.4);
INSERT INTO `rhythm_bar_occurrences` VALUES (37,29,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (38,27,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (38,30,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (46,23,0.6);
INSERT INTO `rhythm_bar_occurrences` VALUES (48,23,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (49,23,0.4);
INSERT INTO `rhythm_bar_occurrences` VALUES (50,23,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (51,23,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (52,23,0.3);
INSERT INTO `rhythm_bar_occurrences` VALUES (53,23,0.15);
INSERT INTO `rhythm_bar_occurrences` VALUES (56,28,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (57,28,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (58,28,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (59,28,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (62,28,0.5);
INSERT INTO `rhythm_bar_occurrences` VALUES (64,28,0.5);

